<?php
declare(strict_types=1);
/**
 * Post Types registration file.
 *
 * @package Starisian\Sparxstar\IAtlas\includes
 */
namespace Starisian\Sparxstar\IAtlas\includes;

use function defined;
use function acf_add_local_field_group;
use function register_taxonomy;
use function add_action;
use function function_exists;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Class Sparxstar3IAtlasPostTypes
 * 
 * Handles the registration of Custom Post Types and ACF fields.
 *
 * @package Starisian\Sparxstar\IAtlas\includes
 * @author Starisian Technologies (Max Barrett) <support@starisian.com>
 * @version 0.6.5
 * @since 0.1.0
 * @license Starisian Technologies Proprietary License (STPL)
 * @copyright Copyright (c) 2024 Starisian Technologies. All rights reserved.
 */
class Sparxstar3IAtlasPostTypes {

    /**
     * Initializes the class and registers hooks.
     */
    public function __construct() {
        $this->sparxIAtlas_register_hooks();
    }


    /**
     * Registers ACF programmatically.
     * 
     * @return void
     */
    public function sparxIAtlas_register_hooks(): void {
           // ACF field group registration code goes here.
          add_action( 'acf/include_fields', function() {
        	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        		return;
        	}
        
        	acf_add_local_field_group( array(
        	'key' => 'group_aiwa_dictionary_main',
        	'title' => 'Dictionary Entry Details',
        	'fields' => array(
        		array(
        			'key' => 'field_69697a7e1194b',
        			'label' => 'Entry UUID',
        			'name' => 'aiwa_entry_uuid',
        			'aria-label' => '',
        			'type' => 'text',
        			'instructions' => 'System created UUID for the header word Entry.',
        			'required' => 1,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => 36,
        			'allow_in_bindings' => 0,
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        			'show_in_graphql' => 1,
        			'graphql_description' => '',
        			'graphql_field_name' => 'entryUuid',
        			'graphql_non_null' => 0,
        		),
        		array(
        			'key' => 'aiwa_field_1',
        			'label' => 'Translation',
        			'name' => 'aiwa_translation',
        			'aria-label' => '',
        			'type' => 'text',
        			'instructions' => 'The meaning of this word in another language. Write what this word means in simple terms.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        		),
        		array(
        			'key' => 'aiwa_field_1a',
        			'label' => 'Translation (English)',
        			'name' => 'aiwa_translation_english',
        			'aria-label' => '',
        			'type' => 'text',
        			'instructions' => 'What this word means in English. Write the English word or phrase that has the same meaning.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        		),
        		array(
        			'key' => 'aiwa_field_1b',
        			'label' => 'Translation (French)',
        			'name' => 'aiwa_translation_french',
        			'aria-label' => '',
        			'type' => 'text',
        			'instructions' => 'What this word means in French. Write the French word or phrase that has the same meaning.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        		),
        		array(
        			'key' => 'aiwa_field_1c',
        			'label' => 'Part of Speech',
        			'name' => 'aiwa_part_of_speech',
        			'aria-label' => '',
        			'type' => 'select',
        			'instructions' => 'What type of word is this? A noun is a person, place, or thing. A verb is an action word. An adjective describes something.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'choices' => array(
        				'noun' => 'Noun',
        				'verb' => 'Verb',
        				'adjective' => 'Adjective',
        				'adverb' => 'Adverb',
        				'pronoun' => 'Pronoun',
        				'preposition' => 'Preposition',
        				'conjunction' => 'Conjunction',
        				'interjection' => 'Interjection',
        				'article' => 'Article',
        				'determiner' => 'Determiner',
        			),
        			'default_value' => false,
        			'allow_null' => 1,
        			'multiple' => 0,
        			'ui' => 0,
        			'return_format' => 'value',
        			'ajax' => 0,
        			'placeholder' => '',
        			'create_options' => 0,
        			'save_options' => 0,
        		),
        		array(
        			'key' => 'aiwa_field_1d',
        			'label' => 'Search String (English)',
        			'name' => 'aiwa_search_string_english',
        			'aria-label' => '',
        			'type' => 'text',
        			'instructions' => 'A combination of the word plus its English meaning. This helps people find this word when they search. Example: \'teranga hospitality welcome\'.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        		),
        		array(
        			'key' => 'aiwa_field_1e',
        			'label' => 'Search String (French)',
        			'name' => 'aiwa_search_string_french',
        			'aria-label' => '',
        			'type' => 'text',
        			'instructions' => 'A combination of the word plus its French meaning. This helps people find this word when they search in French. Example: \'teranga hospitalité accueil\'.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        		),
        		array(
        			'key' => 'aiwa_field_1f',
        			'label' => 'Rating Average',
        			'name' => 'aiwa_rating_average',
        			'aria-label' => '',
        			'type' => 'number',
        			'instructions' => 'The average rating this word has received from users, on a scale from 1 to 5 stars. 5 stars means excellent. This number is usually calculated automatically.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'min' => 1,
        			'max' => 5,
        			'step' => 0.01,
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        		),
        		array(
        			'key' => 'aiwa_field_2',
        			'label' => 'IPA Pronunciation',
        			'name' => 'aiwa_ipa_pronunciation',
        			'aria-label' => '',
        			'type' => 'text',
        			'instructions' => 'How to say this word using special pronunciation symbols (IPA). These symbols show exactly how the word sounds. Example: /tɛɹɑŋɡɑ/. Leave blank if you don\'t know.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        		),
        		array(
        			'key' => 'field_6969745e11941',
        			'label' => 'Phonetic Prounciation',
        			'name' => 'aiwa_phonetic',
        			'aria-label' => '',
        			'type' => 'text',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'allow_in_bindings' => 1,
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        			'show_in_graphql' => 1,
        			'graphql_description' => '',
        			'graphql_field_name' => 'phoneticProunciation',
        			'graphql_non_null' => 0,
        		),
        		array(
        			'key' => 'aiwa_field_3',
        			'label' => 'Audio Recording',
        			'name' => 'aiwa_audio_file',
        			'aria-label' => '',
        			'type' => 'file',
        			'instructions' => 'Upload a sound file of someone speaking this word out loud. This helps people learn how to pronounce it correctly. Use MP3 or WAV format.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'return_format' => 'url',
        			'library' => 'all',
        			'min_size' => '',
        			'max_size' => '',
        			'mime_types' => 'mp3,wav',
        		),
        		array(
        			'key' => 'aiwa_field_4',
        			'label' => 'Word Origin',
        			'name' => 'aiwa_origin',
        			'aria-label' => '',
        			'type' => 'text',
        			'instructions' => 'Where did this word come from? Explain the history of the word or what language it originally came from. Example: \'This word comes from Arabic\'.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        		),
        		array(
        			'key' => 'aiwa_field_5',
        			'label' => 'Word Photo',
        			'name' => 'aiwa_word_photo',
        			'aria-label' => '',
        			'type' => 'image',
        			'instructions' => 'Upload a picture that shows what this word means. If the word means \'tree\', upload a photo of a tree. This helps people understand visually.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'return_format' => 'id',
        			'preview_size' => 'medium',
        			'library' => 'all',
        			'min_width' => '',
        			'min_height' => '',
        			'min_size' => '',
        			'max_width' => '',
        			'max_height' => '',
        			'max_size' => '',
        			'mime_types' => '',
        		),
        		array(
        			'key' => 'aiwa_field_6',
        			'label' => 'Example Sentences',
        			'name' => 'aiwa_example_sentences',
        			'aria-label' => '',
        			'type' => 'repeater',
        			'instructions' => 'Show how this word is used in real sentences. Add 2-3 example sentences with translations. This helps people understand how to use the word correctly.',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'layout' => 'block',
        			'pagination' => 0,
        			'min' => 0,
        			'max' => 0,
        			'collapsed' => 'field_696974c111942',
        			'button_label' => 'Add Sentence',
        			'show_in_graphql' => 1,
        			'graphql_description' => '',
        			'graphql_field_name' => 'aiwaExampleSentences',
        			'graphql_non_null' => 0,
        			'rows_per_page' => 20,
        			'sub_fields' => array(
        				array(
        					'key' => 'field_696974c111942',
        					'label' => 'Sentence Example',
        					'name' => 'aiwa_sentence_example',
        					'aria-label' => '',
        					'type' => 'text',
        					'instructions' => 'Use the word in a complete sentence.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'maxlength' => '',
        					'allow_in_bindings' => 1,
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'show_in_graphql' => 1,
        					'graphql_description' => '',
        					'graphql_field_name' => 'sentenceExample',
        					'graphql_non_null' => 0,
        					'parent_repeater' => 'aiwa_field_6',
        				),
        				array(
        					'key' => 'field_696975ad11943',
        					'label' => 'Sentence Phonetic Pronunciation',
        					'name' => 'aiwa_sentence_phonetic',
        					'aria-label' => '',
        					'type' => 'text',
        					'instructions' => 'The phonetic pronunciation of the complete example sentence.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'maxlength' => '',
        					'allow_in_bindings' => 1,
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'show_in_graphql' => 1,
        					'graphql_description' => '',
        					'graphql_field_name' => 'sentencePhoneticPronunciation',
        					'graphql_non_null' => 0,
        					'parent_repeater' => 'aiwa_field_6',
        				),
        				array(
        					'key' => 'field_6969761311944',
        					'label' => 'Sentence English Translation',
        					'name' => 'aiwa_sentence_english',
        					'aria-label' => '',
        					'type' => 'text',
        					'instructions' => 'The English translation of the example sentence.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'maxlength' => '',
        					'allow_in_bindings' => 0,
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'show_in_graphql' => 1,
        					'graphql_description' => '',
        					'graphql_field_name' => 'sentenceEnglishTranslation',
        					'graphql_non_null' => 0,
        					'parent_repeater' => 'aiwa_field_6',
        				),
        				array(
        					'key' => 'field_6969766611945',
        					'label' => 'Sentence French Translation',
        					'name' => 'aiwa_sentence_french',
        					'aria-label' => '',
        					'type' => 'text',
        					'instructions' => 'The French translation of the example sentence.',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'maxlength' => '',
        					'allow_in_bindings' => 1,
        					'placeholder' => '',
        					'prepend' => '',
        					'append' => '',
        					'show_in_graphql' => 1,
        					'graphql_description' => '',
        					'graphql_field_name' => 'sentenceFrenchTranslation',
        					'graphql_non_null' => 0,
        					'parent_repeater' => 'aiwa_field_6',
        				),
        			),
        		),
        		array(
        			'key' => 'aiwa_field_7',
        			'label' => 'Extract (Long Definition)',
        			'name' => 'aiwa_extract',
        			'aria-label' => '',
        			'type' => 'textarea',
        			'instructions' => 'A detailed explanation of what this word means and how it\'s used. Include any important details, cultural significance, or special meanings. Write as much as needed.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'rows' => 3,
        			'placeholder' => '',
        			'new_lines' => '',
        		),
        		array(
        			'key' => 'aiwa_field_qc_1',
        			'label' => 'Rating',
        			'name' => 'aiwa_rating',
        			'aria-label' => '',
        			'type' => 'select',
        			'instructions' => 'How good is this dictionary entry? Rate it from 1 to 5 stars. This is for internal quality checking only.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'choices' => array(
        				1 => '1 Star',
        				2 => '2 Stars',
        				3 => '3 Stars',
        				4 => '4 Stars',
        				5 => '5 Stars',
        			),
        			'default_value' => false,
        			'allow_null' => 0,
        			'multiple' => 0,
        			'ui' => 0,
        			'return_format' => 'value',
        			'ajax' => 0,
        			'placeholder' => '',
        			'create_options' => 0,
        			'save_options' => 0,
        		),
        		array(
        			'key' => 'aiwa_field_8',
        			'label' => 'Synonyms',
        			'name' => 'aiwa_synonyms',
        			'aria-label' => '',
        			'type' => 'relationship',
        			'instructions' => 'Other words in the dictionary that have similar meanings or are related to this word. Connect this word to other entries so people can discover related vocabulary.',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'aiwa-cpt-dictionary',
        			),
        			'post_status' => '',
        			'taxonomy' => '',
        			'filters' => array(
        				0 => 'search',
        				1 => 'taxonomy',
        			),
        			'return_format' => 'object',
        			'min' => '',
        			'max' => '',
        			'allow_in_bindings' => 1,
        			'elements' => '',
        			'bidirectional' => 0,
        			'show_in_graphql' => 1,
        			'graphql_description' => '',
        			'graphql_field_name' => 'aiwaSynonyms',
        			'graphql_connection_type' => 'one_to_many',
        			'bidirectional_target' => array(
        			),
        		),
        		array(
        			'key' => 'field_6969778611949',
        			'label' => 'Antonyms',
        			'name' => 'aiwa_antonyms',
        			'aria-label' => '',
        			'type' => 'relationship',
        			'instructions' => 'Other words in the dictionary that have the opposite meanings of to this word. Connect this word to other entries so people can discover related vocabulary.',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'aiwa-cpt-dictionary',
        			),
        			'post_status' => '',
        			'taxonomy' => '',
        			'filters' => array(
        				0 => 'search',
        				1 => 'taxonomy',
        			),
        			'return_format' => 'object',
        			'min' => '',
        			'max' => '',
        			'allow_in_bindings' => 1,
        			'elements' => '',
        			'bidirectional' => 0,
        			'show_in_graphql' => 1,
        			'graphql_description' => '',
        			'graphql_field_name' => 'aiwaAntonyms',
        			'graphql_connection_type' => 'one_to_many',
        			'bidirectional_target' => array(
        			),
        		),
        		array(
        			'key' => 'field_696977991194a',
        			'label' => 'Homonyms',
        			'name' => 'aiwa_homonyms',
        			'aria-label' => '',
        			'type' => 'relationship',
        			'instructions' => 'Other words in the dictionary that have sound similar in pronunciation to this word. Connect this word to other entries so people can discover related vocabulary.',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'aiwa-cpt-dictionary',
        			),
        			'post_status' => '',
        			'taxonomy' => '',
        			'filters' => array(
        				0 => 'search',
        				1 => 'taxonomy',
        			),
        			'return_format' => 'object',
        			'min' => '',
        			'max' => '',
        			'allow_in_bindings' => 1,
        			'elements' => '',
        			'bidirectional' => 0,
        			'show_in_graphql' => 1,
        			'graphql_description' => '',
        			'graphql_field_name' => 'aiwaHomonyms',
        			'graphql_connection_type' => 'one_to_many',
        			'bidirectional_target' => array(
        			),
        		),
        		array(
        			'key' => 'aiwa_field_qc_2',
        			'label' => 'QC Status',
        			'name' => 'aiwa_qc_status',
        			'aria-label' => '',
        			'type' => 'select',
        			'instructions' => 'Has this entry been checked for quality? Choose the current status: Pending (not checked yet), Verified (checked and approved), or Needs Fix (needs corrections).',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'choices' => array(
        				'pending' => 'Pending',
        				'verified' => 'Verified',
        				'needs_fix' => 'Needs Fix',
        			),
        			'default_value' => false,
        			'allow_null' => 0,
        			'multiple' => 0,
        			'ui' => 0,
        			'return_format' => 'value',
        			'ajax' => 0,
        			'placeholder' => '',
        			'create_options' => 0,
        			'save_options' => 0,
        		),
        		array(
        			'key' => 'aiwa_field_qc_3',
        			'label' => 'Internal Notes',
        			'name' => 'aiwa_qc_notes',
        			'aria-label' => '',
        			'type' => 'textarea',
        			'instructions' => 'Private notes for staff only. Write any comments, corrections needed, or reminders about this entry. Users will not see these notes.',
        			'required' => false,
        			'conditional_logic' => false,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'maxlength' => '',
        			'rows' => 2,
        			'placeholder' => '',
        			'new_lines' => '',
        		),
        	),
        	'location' => array(
        		array(
        			array(
        				'param' => 'post_type',
        				'operator' => '==',
        				'value' => 'aiwa-cpt-dictionary',
        			),
        		),
        	),
        	'menu_order' => 0,
        	'position' => 'normal',
        	'style' => 'default',
        	'label_placement' => 'top',
        	'instruction_placement' => 'label',
        	'hide_on_screen' => '',
        	'active' => true,
        	'description' => 'Dictionary header word details and metadata.',
        	'show_in_rest' => 1,
        	'display_title' => 'Header Word Entry',
        	'show_in_graphql' => 1,
        	'graphql_field_name' => 'dictionaryEntryDetails',
        	'map_graphql_types_from_location_rules' => 0,
        	'graphql_types' => '',
        ) );
        } );
        
        add_action( 'init', function() {
        	register_taxonomy( 'aiwa-alpha-letter', array(
        	0 => 'sparx-dictionary',
        ), array(
        	'labels' => array(
        		'name' => 'Alpha-Letters',
        		'singular_name' => 'Alpha-Letter',
        		'menu_name' => 'Alpha-Letters',
        		'all_items' => 'All Alpha-Letters',
        		'edit_item' => 'Edit Alpha-Letter',
        		'view_item' => 'View Alpha-Letter',
        		'update_item' => 'Update Alpha-Letter',
        		'add_new_item' => 'Add New Alpha-Letter',
        		'new_item_name' => 'New Alpha-Letter Name',
        		'search_items' => 'Search Alpha-Letters',
        		'popular_items' => 'Popular Alpha-Letters',
        		'separate_items_with_commas' => 'Separate alpha-letters with commas',
        		'add_or_remove_items' => 'Add or remove alpha-letters',
        		'choose_from_most_used' => 'Choose from the most used alpha-letters',
        		'not_found' => 'No alpha-letters found',
        		'no_terms' => 'No alpha-letters',
        		'items_list_navigation' => 'Alpha-Letters list navigation',
        		'items_list' => 'Alpha-Letters list',
        		'back_to_items' => '← Go to alpha-letters',
        		'item_link' => 'Alpha-Letter Link',
        		'item_link_description' => 'A link to a alpha-letter',
        	),
        	'description' => 'Header word first letter indicator.',
        	'public' => true,
        	'show_in_menu' => true,
        	'show_in_rest' => true,
        	'sort' => true,
        	'show_in_graphql' => true,
        	'graphql_single_name' => 'AlphaLetter',
        	'graphql_plural_name' => 'AlphaLetters',
        ) );
        
        	register_taxonomy( 'starmus_tax_dialect', array(
        	0 => 'audio-script',
        	1 => 'audio-recording',
        	2 => 'starmus_transcript',
        	3 => 'starmus_translate',
        ), array(
        	'labels' => array(
        		'name' => 'Dialects',
        		'singular_name' => 'Dialect',
        	),
        	'description' => 'Different ways of speaking the same language in different places.',
        	'public' => false,
        	'hierarchical' => true,
        	'show_ui' => true,
        	'show_in_nav_menus' => true,
        	'show_in_rest' => true,
        	'show_tagcloud' => false,
        	'show_admin_column' => true,
        	'show_in_graphql' => true,
        	'graphql_single_name' => 'Dialect',
        	'graphql_plural_name' => 'Dialects',
        ) );
        
        	register_taxonomy( 'aiwa_domain', array(
        	0 => 'aiwa-cpt-dictionary',
        ), array(
        	'labels' => array(
        		'name' => 'Domains',
        		'singular_name' => 'Domain',
        		'menu_name' => 'Domains',
        		'all_items' => 'All Domains',
        		'edit_item' => 'Edit Domain',
        		'view_item' => 'View Domain',
        		'update_item' => 'Update Domain',
        		'add_new_item' => 'Add New Domain',
        		'new_item_name' => 'New Domain Name',
        		'parent_item' => 'Parent Domain',
        		'parent_item_colon' => 'Parent Domain:',
        		'search_items' => 'Search Domains',
        		'not_found' => 'No domains found',
        		'no_terms' => 'No domains',
        		'filter_by_item' => 'Filter by domain',
        		'items_list_navigation' => 'Domains list navigation',
        		'items_list' => 'Domains list',
        		'back_to_items' => '← Go to domains',
        		'item_link' => 'Domain Link',
        		'item_link_description' => 'A link to a domain',
        	),
        	'description' => 'Semantic domain that connects to the entity.',
        	'public' => true,
        	'hierarchical' => true,
        	'show_in_menu' => true,
        	'show_in_rest' => true,
        	'sort' => true,
        	'show_in_graphql' => true,
        	'graphql_single_name' => 'domain',
        	'graphql_plural_name' => 'domains',
        ) );
        
        	register_taxonomy( 'starmus_tax_language', array(
        	0 => 'audio-script',
        	1 => 'audio-recording',
        	2 => 'starmus_transcript',
        	3 => 'starmus_translate',
        ), array(
        	'labels' => array(
        		'name' => 'Languages',
        		'singular_name' => 'Language',
        	),
        	'description' => 'The language spoken or written in the file.',
        	'public' => false,
        	'hierarchical' => true,
        	'show_ui' => true,
        	'show_in_nav_menus' => true,
        	'show_in_rest' => true,
        	'show_tagcloud' => false,
        	'show_admin_column' => true,
        	'show_in_graphql' => true,
        	'graphql_single_name' => 'Language',
        	'graphql_plural_name' => 'Languages',
        ) );
        
        	register_taxonomy( 'starmus_part_of_speech', array(
        	0 => 'starmus_transcript',
        	1 => 'starmus_translate',
        ), array(
        	'labels' => array(
        		'name' => 'Part of Speech',
        		'singular_name' => 'Part of Speech',
        	),
        	'description' => 'The type of word (Noun, Verb, Adjective).',
        	'public' => false,
        	'hierarchical' => true,
        	'show_ui' => true,
        	'show_in_nav_menus' => true,
        	'show_in_rest' => true,
        	'show_tagcloud' => false,
        	'show_admin_column' => true,
        	'show_in_graphql' => true,
        	'graphql_single_name' => 'PartOfSpeech',
        	'graphql_plural_name' => 'PartOfSpeech',
        ) );
        } );
        
        add_action( 'init', function() {
        	register_post_type( 'aiwa-cpt-dictionary', array(
        	'labels' => array(
        		'name' => 'Dictionaries',
        		'singular_name' => 'Dictionary',
        		'menu_name' => 'Dictionaries',
        		'all_items' => 'All Dictionaries',
        		'edit_item' => 'Edit Dictionary',
        		'view_item' => 'View Dictionary',
        		'view_items' => 'View Dictionaries',
        		'add_new_item' => 'Add Dictionary',
        		'add_new' => 'Add Dictionary',
        		'new_item' => 'New Dictionary',
        		'parent_item_colon' => 'Parent Dictionary:',
        		'search_items' => 'Search Dictionaries',
        		'not_found' => 'No dictionaries found',
        		'not_found_in_trash' => 'No dictionaries found in Trash',
        		'archives' => 'Dictionary Archives',
        		'attributes' => 'Dictionary Attributes',
        		'insert_into_item' => 'Insert into dictionary',
        		'uploaded_to_this_item' => 'Uploaded to this dictionary',
        		'filter_items_list' => 'Filter dictionaries list',
        		'filter_by_date' => 'Filter dictionaries by date',
        		'items_list_navigation' => 'Dictionaries list navigation',
        		'items_list' => 'Dictionaries list',
        		'item_published' => 'Dictionary published.',
        		'item_published_privately' => 'Dictionary published privately.',
        		'item_reverted_to_draft' => 'Dictionary reverted to draft.',
        		'item_scheduled' => 'Dictionary scheduled.',
        		'item_updated' => 'Dictionary updated.',
        		'item_link' => 'Dictionary Link',
        		'item_link_description' => 'A link to a dictionary.',
        	),
        	'description' => 'Public word entries for dictionaries.',
        	'public' => true,
        	'show_in_rest' => true,
        	'menu_icon' => 'dashicons-book-alt',
        	'supports' => array(
        		0 => 'title',
        		1 => 'author',
        		2 => 'comments',
        		3 => 'editor',
        		4 => 'excerpt',
        		5 => 'revisions',
        		6 => 'page-attributes',
        		7 => 'thumbnail',
        		8 => 'custom-fields',
        		9 => 'post-formats',
        	),
        	'taxonomies' => array(
        		0 => 'starmus_part_of_speech',
        		1 => 'starmus_tax_language',
        		2 => 'starmus_tax_dialect',
        		3 => 'aiwa_domain',
        		4 => 'aiwa-alpha-letter',
        	),
        	'delete_with_user' => false,
        	'show_in_graphql' => true,
        	'graphql_single_name' => 'dictionary',
        	'graphql_plural_name' => 'dictionaries',
        ) );
        } );
        // End of sparxIAtlas_register_hooks
    }
}
