permissions:
    contents: read
name: Security Checks
on:
    schedule:
        - cron: '0 0 * * 0'
jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
            - name: Composer audit
              run: composer audit || true
            - name: pnpm audit
              run: pnpm audit || true
